### ISSUE TITLE
Random initial state 

### ISSUE THREAD

**Issue by Louis-PaulHenry** [pasqal-io/Pulser#102]
In order to check the stability of the emulator, it could be useful to be able to input a random initial state with a simple caracterisation (say a product state were each atom is in <img src="https://render.githubusercontent.com/render/math?math=$\sqrt{(1-r_0^2)}e^{i \theta_g}{\bf g} \%2B r_0 e^{i \theta_r}{\bf r}$">, with r_0 an input from the user)

**Comment by lhenriet** [comment]
Hi  ! I think it's already possible to provide an initial_state in the run method. By the way, I feel it would be good to clarify (in the docstring?) that this feature is only possible for emulation's purposes.
