### ISSUE TITLE
Checking for empty dictionary in Register constructor

### ISSUE THREAD

**Issue by darcangelomauro** [pasqal-io/Pulser#137]
When creating a register, the constructor looks at the first element of the qubits dictionary to know the size. I think there should be an exception raised if the user passes an empty dictionary

**Comment by HGSilveri** [comment]
Hi @darcangelomauro , that's a good point! Are you up for making a PR with that?

**Comment by darcangelomauro** [comment]
Hi, I don't think I have the permissions yet

**Comment by HGSilveri** [comment]
You should have received an invite.
