### ISSUE TITLE
Display area and phase of pulse on it

### ISSUE THREAD

**Issue by romainfd** [pasqal-io/Pulser#149]
As the area of a pulse is a key element of its effect, displaying the area on the pulse when drawing the sequence could make it easier to interpret.

For example, Figure 8 of the [recent Pulser paper](https://arxiv.org/pdf/2104.15044.pdf) would be more self-explanatory with such a feature as section "3.2.5 Composing the Sequence" is focused on building pulses of specific areas.
![image](https://user-images.githubusercontent.com/32517197/117844392-eeaf7900-b27f-11eb-9674-b17a7dbe8f04.png)

However, this could make the drawing quite crowded. Perhaps a flag, a formatting option or/and a bit of logic to better display pi, 2.pi, ... values could help with that?

**Comment by HGSilveri** [comment]
This would indeed be quite useful, and I have considered it before. However, as you point out, it will get quite crowded. Not only that, the space available for writing this information will decrease as the sequence increases, eventually reaching a point where you no longer have enough space to write down the area and it will just pile on, potentially making a mess. 

I don't have a great idea of how to handle this robustly and automatically, but perhaps we don't have to if we make this optional, with the default being not to do it. In that way, the user has to purposefully choose to do it and will understand why it looks bad if that ends up happening.

**Comment by HGSilveri** [comment]
A clarification of this issue's objective:

When drawing a `Sequence`, add the option of **displaying the area and phase**, as multiples of π, of the various amplitude waveforms. The placement of such labels is not set in stone, but should be as robust to different sizes of the pulses as possible.

**Utility**:
This will allow the identification of the pulses as rotations around a Bloch sphere axis (cos(phase), -sin(phase), 0), by an angle = area of the pulse, just from looking at the sequence plot.

**Comment by Yash-10** [comment]
I am finding this issue interesting to solve. Hence, I am going to attempt to solve it.

Thanks!

**Comment by HGSilveri** [comment]
Successfully solved by @Yash-10
