### ISSUE TITLE
Adding several noise models in the simulation method

### ISSUE THREAD

**Issue by julien-bremont** [pasqal-io/Pulser#151]
Hi,

We're currently working with @sebgrijalva on noise models related to  
- SPAM (State Preparation And Measurement) errors
- Doppler-induced frequency shifting that affects the laser's detuning 
- Amplitude noise on gaussian lasers

We're also adding a possibility to simulate a laser sequence several times and average the results, since noise parameters are different at each run, to better simulate experiments in the lab. You may also change several noise parameters, be it the Doppler shift standard deviation, false-positive (negative) probabilities, etc.

**Comment by HGSilveri** [comment]
Solved with #197 and #199 .
