### ISSUE TITLE
Add type hints, and use mypy to enforce in CI

### ISSUE THREAD

**Issue by karalekas** [pasqal-io/Pulser#16]
Python is a dynamically-typed language (see: [duck typing](https://en.wikipedia.org/wiki/Duck_typing)), but Python 3.5 and [pep-484](https://www.python.org/dev/peps/pep-0484/) introduced type hints as a way to annotate Python code with types. These are not enforced by the language at runtime, but they can be checked by third-party libraries such as [mypy](https://mypy.readthedocs.io/en/stable/). The impetus for adding type hints and using mypy is that they generally encourage developers to write saner, simpler code (the flexibility of Python is a double-edged sword). This issue is mostly about good code style and therefore is optional -- it doesn't block CI setup (but once it is complete, the CI can be used to do this type checking automatically).

**Comment by TripleR47** [comment]
Hi @HGSilveri  @karalekas, I went through the issue and would like to work on it. I have a few questions, I found this [GitHub Action](https://github.com/marketplace/actions/lint-action) which can be used to implement the type hint ci, so can it be used? or do it need to be implemented using shell script?

**Comment by LaurentAjdnik** [comment]
Hi @TripleR47, I've done it for the `Register` class (I will PR #132 tomorrow) but I did it manually 🤨, while adding "Enhanced ErrorValue messages" (#148) at the same time.

**Comment by HGSilveri** [comment]
Hi @TripleR47, no preference regarding how the mypy checks are occur, as long as they are programmed into the existing workflow, if that's what you're asking. But bear in mind that is not the crux of the PR, but rather going through the existing code and adding the appropriate type hints to each function and method. After that's done, then you can incorporate `mypy` into the CI routine. 
I realize it's quite a bit of work, but that's why there's a bounty on it!

**Comment by TripleR47** [comment]
Okay, I'll ask in the unitaryHack's server if anyone wants to collaborate on this issue. Can it be assigned to me?

**Comment by TripleR47** [comment]
Hi @LaurentAjdnik, wanna collaborate on this issue?

**Comment by LaurentAjdnik** [comment]
> Hi @LaurentAjdnik, wanna collaborate on this issue?

👍

**Comment by TripleR47** [comment]
> > Hi @LaurentAjdnik, wanna collaborate on this issue?
> 
> 👍

Are you in unitaryfund's discord server? If you are then DM me on discord, we can discuss further on this.

**Comment by HGSilveri** [comment]
@TripleR47 @LaurentAjdnik So, can I assign it to you both?

**Comment by TripleR47** [comment]
Sure

**Comment by LaurentAjdnik** [comment]
> @TripleR47 @LaurentAjdnik So, can I assign it to you both?

Yup!

Your feedback on #155, in which I added type hints, will be insightful for the current issue.

Then, we can sync with @TripleR47.

**Comment by TripleR47** [comment]
> > > Hi @LaurentAjdnik, wanna collaborate on this issue?
> > 
> > 
> > 👍
> 
> Are you in unitaryfund's discord server? If you are then DM me on discord, we can discuss further on this.

@LaurentAjdnik

**Comment by LaurentAjdnik** [comment]
@TripleR47: Nope, not on Discord. I'm waiting for the feedback on #155 and we can move on from there.

Adding type hints will be pretty straightforward. Maybe we can dispatch classes between us.

@HGSilveri: Will you be in charge of adding mypy to CI workflow ?

**Comment by HGSilveri** [comment]
@LaurentAjdnik : I'll review #155 first thing on Monday. And yes, I can add it to the CI no problem. I would advise you to use it to test your own typing as you go. Did you try it already on #155?

**Comment by LaurentAjdnik** [comment]
Running MyPy on #155 (screenshots below):
* `Register` class: No errors in my code
* `Register` class: Error in `from_coordinates()` on `qubits = dict(enumerate(coords))`
* A few errors in other modules
* Lots of errors on imports with modules having no type hints

With the `--ignore-missing-imports` option:

![MyPy-2021-05-16ignore](https://user-images.githubusercontent.com/83899250/118389170-deedb700-b628-11eb-9bbb-8e4304f2968d.png)

Without the `--ignore-missing-imports` option:

![MyPy-2021-05-16](https://user-images.githubusercontent.com/83899250/118388730-6685f680-b626-11eb-9a3e-7498afe62f1d.png)

**Comment by LaurentAjdnik** [comment]
Hi @TripleR47!

Have you been working on it ?

PR #155 has been approved and type-checked with MyPy beforehand. We could use it as an inspiration.

**Comment by TripleR47** [comment]
Yes, I have been going through mypy and Pulser documentations and have started working on the devices module.

@LaurentAjdnik, let's split up the rest of the modules.

**Comment by LaurentAjdnik** [comment]
> Yes, I have been going through mypy and Pulser documentations and have started working on the devices module.
> 
> @LaurentAjdnik, let's split up the rest of the modules.

Great! I'll start working on `waveforms.py` then.

**Comment by LaurentAjdnik** [comment]
Hi again @TripleR47!

I just PR-ed #163 on `waveforms.py` for a feedback from experts, that we can use for further work.

**Comment by LaurentAjdnik** [comment]
Hi again @TripleR47 and @HGSilveri, I start working on `sequence.py`.

**Comment by TripleR47** [comment]
Okay, I'm almost done with the devices module, will start working on parametrized and simulation after that.

**Comment by LaurentAjdnik** [comment]
Great! I'll start working on `_seq_drawer.py`, `channels.py` and `pulse.py` so that the root directory is done.

**Comment by TripleR47** [comment]
Okay! I'm done with the parametrized module, start working on simulation next.

**Comment by HGSilveri** [comment]
Hi @LaurentAjdnik , @TripleR47 ! Glad to see you're making progress. 

I just wanted to clarify a few things: 
- The order of the PRs  should be in order of increased dependency on other modules. This means, for example, that `pulse.py` should be merged after `waveforms.py` but before `sequence.py`. Also, `pulser.parametrized` should come soon as it is frequently imported but does not import any other module. Inversely, `pulser.simulation` should be one of the last modules to be merged, as it is not imported but imports `Sequence`, which in turn imports almost everything else. Thus, the next modules to merge should be:
    1. `pulser.channels` and `pulser.parametrized`
    2. `pulser.waveforms`
    3. `pulser.pulse`
- You'll find in #168 that I setup a config file for `mypy`. Once that PR is merged with `develop`, you can start type checking locally just by running `mypy` inside the `Pulser` folder, but make sure you have `numpy >= 1.20` installed beforehand.
- You'll also find that I added some type checks in #168, mostly to get rid of all the `mypy` errors. Beware of potential merge conflicts.

Keep up the good work!

**Comment by TripleR47** [comment]
Okay @HGSilveri, @LaurentAjdnik if you haven't started working on `pulse.py` yet, can I take over that module? After that, I can go for `pulser.simulation`.

**Comment by TripleR47** [comment]
Okay, I have also finished the `pulser.simlation`. Let's start working on the test module then.

**Comment by TripleR47** [comment]
Hey @LaurentAjdnik, which test modules are you working on?

**Comment by LaurentAjdnik** [comment]
> Hey @LaurentAjdnik, which test modules are you working on?

Hi @TripleR47, I'm done with all files in the root directory.

I haven't planned working on test files.

@HGSilveri: Does it make sense anyway?

**Comment by HGSilveri** [comment]
> @HGSilveri: Does it make sense anyway?

I would say no, not really.

**Comment by TripleR47** [comment]
Okay

**Comment by HGSilveri** [comment]
So, I was convinced that using "parametrized generics" for type-hinting using built-ins (e.g. `dict[str, Any]` instead of `Dict[str, Any]`) would only work from Python 3.9, but apparently, according to [PEP 585](https://www.python.org/dev/peps/pep-0585/) that's not the case if `annotations` are imported from `__future__`, which can be done since Python version 3.7.

I don't like the inconsistency of having both forms, so I guess we should adopt the most modern one throughout, which is to use the built-ins (i.e., `dict`, `list`, `tuple`, ...). 

I have been asking you to do the opposite up until now, so it's only fair I make a PR enforcing these changes for all the type-hints that have already been merged. However, it would be good if you could change this on the PRs that are still open.

**Comment by TripleR47** [comment]
Okay

**Comment by TripleR47** [comment]
Okay, and what about the special types like Callable, Union etc. Do we have their alternatives in the built-ins?

**Comment by HGSilveri** [comment]
No, those stay the same. Refer to [this list](https://www.python.org/dev/peps/pep-0585/#implementation) for the built-in generics that replace those in `typing`.

**Comment by TripleR47** [comment]
Okay, thanks!

**Comment by HGSilveri** [comment]
@TripleR47 : From that list, notice that `Callable` actually does change (should be imported from `collections.abc` instead).

**Comment by HGSilveri** [comment]
Solved by @LaurentAjdnik and @TripleR47 , thank you both for your patience and hard work!

**Comment by TripleR47** [comment]
@HGSilveri, thanks for your guidance! 😃
