### ISSUE TITLE
Notebook explaining the visualization options of Sequences

### ISSUE THREAD

**Issue by sebgrijalva** [pasqal-io/Pulser#164]
Now that new functionalities are being added to the `Sequence.draw()` method, it would be nice to have a Notebook explaining the different characteristics, including `sampling_rate` (and its effect in the effective sequence - #122 ), and the role of `t_list` and `eval_t` from the point of view of the sequence being simulated.

This can be also expanded when #149 is ready

**Comment by HGSilveri** [comment]
These will rather be displayed on the notebooks, when pertinent. Current status:
- `draw_phase_shifts` is shown on the tutorial on Phase Shifts and VZ Gates
- `draw_interp_pts` is shown on the tutorial on Interpolated Waveforms (#224)
- `draw_phase_area` should be included on a tutorial on digital quantum computing (the CZ implementation, perhaps?)
- `Simulation.draw()` will be shown on the tutorial on Noisy Simulations (#216)
