### ISSUE TITLE
Simulation Configuration as a separate class.

### ISSUE THREAD

**Issue by sebgrijalva** [pasqal-io/Pulser#184]
>Just an idea here, open for discussion. 
>
>The Simulation class is getting big. What about separating from the class all the configs elements related to noise >? Then, we could provide the necessary elements at initialization. Something like my_sim = Simulation(sequence, >noise_config).

_Originally posted by @lhenriet in https://github.com/pasqal-io/Pulser/pull/161#discussion_r642857978_

This is an interesting suggestion. I already went into this way with the refactoring I was proposing in the Simulation class a couple of weeks ago (#152). A `SimConfig` class (inside the `pulser.simulation` module) would include at least two sets of instructions: 

- The *Noise* configuration for the simulation (Which would work closely with the `Device` specs)
- The *Numerical* configuration, which would contain the settings for the particular solver (evaluation lists, mesh settings, other options for future solvers --hat tip to tensor network/montecarlo/QuantumOptics.jl sims).

There could be then other sets of configs added later, or more specific subclases.

**Comment by julien-bremont** [comment]
I added a new SimConfig class in an attempt to be clearer. It encapsulates noise types, temperature field, number of runs, and solver options, and is part of the simulation module.
