### ISSUE TITLE
Inconsistant behavior when simulating a pulse after a delay

### ISSUE THREAD

**Issue by rbstsai** [pasqal-io/Pulser#207]
A bug is detected while some simulations were run and analyzed. We have narrowed it down, and it seems that the delay time has a role to play in the final state. This isn't expected, given that a delay time in the beginning of a sequence shouldn't influence anything.

Below is the implementation of a simple quantum circuit using pulser. 
The function create_sequence_with_delay takes the delay_time in nanoseconds and creates a sequence with one single qubit and apply a gate U(-pi/2,pi/2,pi/2). We'll see the effect of different delay times by drawing a graph.

```
import numpy as np
import matplotlib.pyplot as plt
from qutip import Qobj

from pulser import Pulse, Sequence, Register
from pulser.waveforms import BlackmanWaveform
from pulser.devices import Chadoq2
from pulser.simulation import Simulation


def create_sequence_with_delay(delay_time):
    qubits = {'q1': (0, 0)}
    reg = Register(qubits)
    seq = Sequence(reg, Chadoq2)
    seq.declare_channel('dig', 'raman_local', 'q1')

    if delay_time:
        seq.delay(delay_time, 'dig')

    seq.target('q1', 'dig')
    wf = BlackmanWaveform(200, area=np.pi/2)
    pulse = Pulse.ConstantDetuning(amplitude=wf, detuning=0, phase=np.pi/2)
    seq.add(pulse, 'dig')

    seq.measure(basis='digital')

    return seq


ideal_state = Qobj([[1/np.sqrt(2)], [-1/np.sqrt(2)]])
projection_list = []
delay_range = range(16, 400, 4)
for delay in delay_range:
    seq = create_sequence_with_delay(delay)
    sim = Simulation(seq)
    res = sim.run()
    projection_list.append(
        ideal_state.overlap(res.get_final_state(ignore_global_phase=True))
        )

plt.figure()
plt.plot(list(delay_range), np.abs(projection_list), '--o')
plt.xlabel(r"delay time [ns]", fontsize=14)
plt.ylabel(r"inner product with the ideal state", fontsize=14)
plt.show()
```

Below is the result, the ideal state is what we should be expecting:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/77646328/122569563-295cbc00-d04b-11eb-8f1e-41d9a5c821f6.png">

Let's see the sequence corresponding to a delay time of 100 ns.
<img width="994" alt="image" src="https://user-images.githubusercontent.com/77646328/122569866-7476cf00-d04b-11eb-978e-f109b7666b25.png">

The delay time only determines the window in the beginning.

**Comment by sebgrijalva** [comment]
Hi!

This doesn't seem to be a bug in Pulser, but a matter of setting QuTiP's solver options according to your simulation. In your case, try `sim.run(first_step=1)`. Since you are adding a `delay`, the solver chooses automatically the initial step by default and thinks it has nothing ahead. You may check out other parameters in their documentation (https://qutip.org/docs/latest/guide/dynamics/dynamics-options.html)
