### ISSUE TITLE
Documentation theme

### ISSUE THREAD

**Issue by lvignoli** [pasqal-io/Pulser#321]
I suggest using a more modern documentation style, to increase legibility but also attractiveness ✨.

Moreover, the current readthedocs `sphinx_rtd_theme` style behaves poorly on large screen size:
![Capture d’écran 2022-02-07 à 17 00 04](https://user-images.githubusercontent.com/97944962/152824482-fc4cde5a-cec5-41ff-8133-e002eabe5cbb.png)
Compare this to for example [`furo`](https://sphinx-themes.org/sample-sites/furo/):
![Capture d’écran 2022-02-07 à 16 58 28](https://user-images.githubusercontent.com/97944962/152824114-4bee8891-1d53-4251-80d2-29fb54de8393.png)

There are many good themes on [sphinx-themes.org](https://sphinx-themes.org). I suggests using [`furo`](https://sphinx-themes.org/sample-sites/furo/)—for which `black` docs have recently changed by the way—but it really is up to us.

**Comment by HGSilveri** [comment]
I agree that the large screen size behaviour is annoying, but I must say I'm not a big fan of the `furo` design. I also think a point should be made in favour of ReadTheDocs for its widespread use and consequent user-familiarity. 
How about we select a few candidate themes and have an informal election?

**Comment by lvignoli** [comment]
Yes ReadTheDocs is widespread, but for me it is not a pro actually ; it shouts "good old python" rather than "up to date maintained package". 

> How about we select a few candidate themes and have an informal election?

It's really a matter of taste, so that would be the nicest way to do so!

**Comment by lvignoli** [comment]
Some alternatives, see [sphinx-themes.org](https://sphinx-themes.org) for a full list:

**ReadTheDocs**
![152824482-fc4cde5a-cec5-41ff-8133-e002eabe5cbb](https://user-images.githubusercontent.com/97944962/155560196-4cb6a141-041b-4649-888a-ddec550975a5.png)

**Books**
![Capture d’écran 2022-02-24 à 16 49 44](https://user-images.githubusercontent.com/97944962/155560349-5ad985f7-e8d0-40a9-9f61-fa14c97e8b3c.png)


**Furo**
![152824114-4bee8891-1d53-4251-80d2-29fb54de8393](https://user-images.githubusercontent.com/97944962/155560220-7f5ccea0-c6f3-49d9-9cc6-f967892ed74c.png)

**Press**
![Capture d’écran 2022-02-24 à 16 56 53](https://user-images.githubusercontent.com/97944962/155560394-ce36b9ed-1d9e-4364-a623-9c3dadfdb6bf.png)
