### ISSUE TITLE
Raise custom exception when serialized sequence validation fails

### ISSUE THREAD

**Issue by MatthieuMoreau0** [pasqal-io/Pulser#341]
Right now, a `SystemError` is raised when the validation of a serialized sequence fails as seen here in the [code](https://github.com/pasqal-io/Pulser/blob/develop/pulser/json/supported.py#L88). 

Looking at the documentation of SystemError in the [python built-in exceptions](https://docs.python.org/3/library/exceptions.html#SystemError) this exception doesn't really seem to match the issue we want to raise to the user. 

I feel bothered to try and catch a `SystemError` to detect invalid sequences because that error could be raised for critical reason tied to the interpreter totally unrelated to the sequence validation. Is it possible to define a new custom exception and raise it when validation fails, such as I could import it and catch for that specific issue when it occurs. 

Any thoughts on that idea ?  If it sounds good to you, I can take care of implementing this change as it should be quite minimal.

**Comment by HGSilveri** [comment]
Yes, that's fine with me! And thanks for offering to take care of it.

I would suggest something like `SerializationError`, or `PulserSerializationError` to be even more specific. You can place it inside the `pulser.json` module.
