### ISSUE TITLE
Automatic packaging

### ISSUE THREAD

**Issue by HGSilveri** [pasqal-io/Pulser#363]
Once #362 goes through, it would be nice to have some automatic packaging routine and some CI test on it.

The packaging process is a bit unorthodox because we have three different PyPI distributions under the same repository:
- `pulser-core`, which contains the `pulser` package
- `pulser-simulation`, which contains the `pulser_simulation` package
- `pulser`, which has no package in itself but installs a specific version of `pulser-core` and `pulser-simulation`

AFAIK, [`cirq`](https://github.com/quantumlib/Cirq) has a similar setup, so it might be worth looking into for inspiration.

**Comment by fred5825** [comment]
@HGSilveri Hi can give this a shot would you be available to talk about this some more?

**Comment by HGSilveri** [comment]
Hi @fred5825 , of course! I'll send you a message on Discord. Once you've decided you wanted to tackle this let me know and I'll assign it to you
