### ISSUE TITLE
Tutorial on modulated output sequence creation and simulation

### ISSUE THREAD

**Issue by HGSilveri** [pasqal-io/Pulser#367]
A tutorial for the docs showcasing how to use the output modulation features. 

Should be done after #315.

**Comment by arthurfaria** [comment]
Hi! Thanks @HGSilveri

**Comment by HGSilveri** [comment]
Awesome! 
By the way, the features needed for the simulation part are being introduced in PR #390, you can take a look already if you want. 
Relevantly here, you'll have an extra option in `Simulation()` that let's you choose whether you want to simulate with the input or the modulated output. All you'll need to do is choose this enable option, like so:
```python
sim = Simulation(seq, with_modulation=True)
```
If then e.g. you draw the simulation with `sim.draw()`, you'll see the output pulses will appear.

**Comment by arthurfaria** [comment]
Thanks for the remark!
