### ISSUE TITLE
Add saving possibility to register layout draw method 

### ISSUE THREAD

**Issue by LucasGitQ** [pasqal-io/Pulser#391]
When drawing a Register, there is the possibility to save the produced figure but there is not the same thing for the new layout object. 
<img width="596" alt="pull" src="https://user-images.githubusercontent.com/71789668/183038367-bbe0862c-7ddb-4b70-887c-299d55bf5e82.png">

**Comment by HGSilveri** [comment]
Good point @LucasGitQ ! Do you need this feature soon or can we leave it for newcomers?

**Comment by LucasGitQ** [comment]
I can do without it, no problem. We can leave it for newcomers !

**Comment by HGSilveri** [comment]
@a-corni , do you want to tackle this one as a first issue?

**Comment by a-corni** [comment]
@HGSilveri Let's have a look to this !
