### ISSUE TITLE
Wrong qubit ID

### ISSUE THREAD

**Issue by gwennole-cournez** [pasqal-io/Pulser#426]
While running the "creating_sequence.ipynb" notebook, I noticed that when a register is created using `Register.square`, qubits ID are created with the first axis = x and the second axis = y. 
All the other methods are using the first axis = y and the second axis = x and the doc say the same: https://pulser.readthedocs.io/en/stable/tutorials/creating.html#1.-Creating-the-Register

![wrong_ids](https://user-images.githubusercontent.com/119879532/205688039-3b0416bc-cb5c-4ef8-8ef5-c78e5f5c8ba7.png)
![good_ids](https://user-images.githubusercontent.com/119879532/205688048-19b5821d-d593-46b0-9d64-db8cb0dd25d1.png)

**Comment by HGSilveri** [comment]
Yes, that's true. I agree that it's not consistent, but there is no established convention on how qubits in a Register are ordered.
Is the issue the fact that this might be misleading or is it something else?

**Comment by gwennole-cournez** [comment]
I thought a convention was defined, so yes It can be misleading

**Comment by HGSilveri** [comment]
Maybe you are thinking of the convention on the `RegisterLayout`? There is convention on the order of the traps there: https://pulser.readthedocs.io/en/latest/tutorials/reg_layouts.html

How a user chooses to put qubits in these traps and label them is up to them. The qubit IDs don't even need to have numbers in them, so I'm not sure there is a way to enforce a consistent ordering convention there (or even that we should).
