### ISSUE TITLE
Update method for Quantum Master Equation

### ISSUE THREAD

**Issue by sebgrijalva** [pasqal-io/Pulser#427]
When calling the `_run_solver()` method in `Simulation` (line 880 in `Simulation.py`), a fix was introduced for using the `mesolve()` method from QuTiP, in which a `Liouvillian` object was created before calling the solver.

In the meantime, the creation of the Hamiltonian and initial state was updated in QuTiP, so the "fix" should be updated with the recommended creation.

**Comment by sebgrijalva** [comment]
@Varda-star  This is one of the improvements on the module for you :)

**Comment by Varda-star** [comment]
I jump on it!

**Comment by Varda-star** [comment]
In the meantime, the creation of the Hamiltonian and initial state was updated in QuTiP, so the "fix" should be updated with the recommended creation. // What are these updates precisely?

**Comment by sebgrijalva** [comment]
Don't create the `qutip.liouvillian()` object in line 880, instead call the `mesolve()` method directly with the Hamiltonian and collapse operators.

**Comment by Varda-star** [comment]
Copied that

**Comment by Varda-star** [comment]
I open a PR about it.
