### ISSUE TITLE
pulser-core 0.8.0 pins jsonschema to 4.4.0

### ISSUE THREAD

**Issue by picbeats** [pasqal-io/Pulser#454]
pulser-core 0.8.0 pins jsonschema to 4.4.0 causing conflicts with other packages due to missing `format-nongpl` extension. 
Removing of the constrain does not make any test fail. 
Suggested to remove jsonschema constrain.

**Comment by HGSilveri** [comment]
Hi @picbeats , thanks for raising this up!
This seems sensible, as far as I can remember we don't have a strong reason to pin the `jsonschema` version. 
Is this urgent or have you managed to circumvent this issue for now?

**Comment by picbeats** [comment]
It's not urgent, but required a workaround in a build pipeline, so would be nice to fix it with a next release.

**Comment by HGSilveri** [comment]
Alright, no problem!

**Comment by HGSilveri** [comment]
@picbeats The change has been released in v0.9.0, feel free to update your pipeline.

**Comment by picbeats** [comment]
Thanks, that's worked. Still have issues with requests and pasqal-sdk vs. jupyterlab-server
