### ISSUE TITLE
[DOC] Abstract representation

### ISSUE THREAD

**Issue by MatthieuMoreau0** [pasqal-io/Pulser#498]
Hello I was looking in the docs for some paragraph about the abstract representation of a sequence but couldn't find any mention of it; maybe I missed it. There is this [section](https://pulser.readthedocs.io/en/stable/tutorials/serialization.html) about serialization but it uses the "python representation". 

I thought we wanted to encourage as much as possible using the abstract representation so it could be nice to have a small description in there!

**Comment by HGSilveri** [comment]
Very good point, we should indeed change that tutorial!
