### ISSUE TITLE
Fix compatibility with Numpy 1.25

### ISSUE THREAD

**Issue by HGSilveri** [pasqal-io/Pulser#536]
The latest Numpy release (1.25.0) broke some our CI tests in Python >= 3.9. 
I didn't check why exactly, but we should fix these issues if possible or avoid this release otherwise.

**Comment by awennersteen** [comment]
If you can't fix quickly could you push a new version just for constraining the version <1.25?

we also had some internal things fail too, not sure if it's just because of Pulser output yet or also what we do internally

**Comment by HGSilveri** [comment]
Yes, I'll have a patch released today

**Comment by HGSilveri** [comment]
Fixed in version 0.13.1
