### ISSUE TITLE
Upgrade qutip to drop the restriction on scipy

### ISSUE THREAD

**Issue by HGSilveri** [pasqal-io/Pulser#542]
In #540, we restricted the SciPy version to be `<1.11` because it was breaking Qutip. Now that Qutip 4.7.2 was released with a fix for this, we can relax that restriction by enforcing that `qutip ~= 4.7.2`.

**Comment by a-corni** [comment]
Why should it be `qutip ~= 4.7.2` and not `qutip >= 4.7.2` ? Because everything works with version 4 ?

**Comment by HGSilveri** [comment]
Well, only because I'm kind of tired of qutip dependencies always conflicting with other packages, this way it is more controlled (since `qutip ~= 4.7.2` is equivalent to   `qutip >= 4.7.2, <4. 8`)

**Comment by a-corni** [comment]
Great ! I was just wondering haha
