### ISSUE TITLE
Handling deprecation of `jsonschema.RefResolver` in latest release of jsonschema

### ISSUE THREAD

**Issue by a-corni** [pasqal-io/Pulser#547]
In the [latest release of `jsonschema`](https://pypi.org/project/jsonschema/4.18.0/), `RefResolver` was deprecated which makes our tests fail in `deserializer.py`.
The [referencing library](https://github.com/python-jsonschema/referencing/) should be used instead.
![image](https://github.com/pasqal-io/Pulser/assets/61453516/ae6c4880-1e40-428c-814a-fa8229361f00)

**Comment by HGSilveri** [comment]
Yeah, this is quite annoying. I'm on it

**Comment by a-corni** [comment]
Okay I was about to go for it otherwise.

**Comment by a-corni** [comment]
Okay let's go for this.
