### ISSUE TITLE
Add function to validate that a given sequence's register matches the pre calibrated layout of a device

### ISSUE THREAD

**Issue by MatthieuMoreau0** [pasqal-io/Pulser#577]
Given a `Sequence` and a `Device` object, I would like to be able to assert that the register of the sequence derives from the pre calibrated layouts of the device (if any). If no pre-calibrated layouts on the device then the function would return always True.

We initially thought about implementing our own logic but I think it would be better to have a properly tested function in the pulser repo directly that can be reused in any project and would be kept in sync with future developments of Pulser. For reference, here's the logic we initially went for:

```python
if device.pre_calibrated_layouts:
    if (
        sequence.register.layout is None
        or sequence.register.layout.static_hash()
        not in [
            layout.static_hash() for layout in device.pre_calibrated_layouts
        ]
    ):
        raise ValueError(
            "The sequence's register should derive from one of the device pre-calibrated layouts."
        )
```

**Comment by HGSilveri** [comment]
> If no pre-calibrated layouts on the device then the function would return always True.

I'm not sure about this part... Imo, if you're trying to check that a register came from a layout in a Device's pre-calibrated layouts but that Device has no pre-calibrated layouts, I would expect either `False` or an error, not `True`.

**Comment by MatthieuMoreau0** [comment]
> I'm not sure about this part... Imo, if you're trying to check that a register came from a layout in a Device's pre-calibrated layouts but that Device has no pre-calibrated layouts, I would expect either False or an error, not True.

Yeah I see how this is confusing, let's go with False in that case!

> Ok, so you'd prefer that the input to the method is the register, not the layout?

If possible yes, this would make my life marginally easier as I wouldn't have to explicitly check if the register has a layout before running that function

**Comment by HGSilveri** [comment]
My idea for this was to add two new methods to `Device`:

- [ ] `Device.is_calibrated_layout(layout: RegisterLayout)`: Checks whether a layout is within the calibrated layouts.
- [ ] `Device.register_is_from_calibrated_layout(register: BaseRegister)`: Checks whether the register was constructed from a pre-calibrated layout (ie checks if it has a layout AND `is_calibrated_layout(layout)`)

This way, we can have the possibility to check whether a layout is calibrated while also having the convenience of checking directly from the register.
