### ISSUE TITLE
Access to myQLM-Pulser integration code for FZJ

### ISSUE THREAD

**Issue by ccalaza** [pasqal-io/Pulser#612]
Good morning,

on behalf of the Quantum Information Processing group at the Juelich Supercomputing Centre (FZJ) and in absence of a more direct route of communication, I hereby request access to the Pasqal side of the code linking QLM and Pasqal HW. Once I get access to this code I can proceed with the HPC integration work being carried out at our site for the Pasqal device to be hosted here.

I'd also be very thankful if the responsible contact person (according to Philippe from TGCC this could be @a-corni ?) drops me an email at c.gonzalez.calaza_at_fz-juelich.de for future communications for which the GitHub issues page may not be so well suited.

Many thanks in advance!

X
Carlos

**Comment by a-corni** [comment]
Hi Carlos !
Thanks for reaching us, the GitHub issues page is indeed not suited for this, I will reach out to you by email.
