### ISSUE TITLE
Integrating ReviewNB

### ISSUE THREAD

**Issue by HGSilveri** [pasqal-io/Pulser#66]
Now that we are open-source, we can integrate [ReviewNB](https://www.reviewnb.com/) for free to facilitate the review of Jupyter notebooks. What do you think, @lhenriet  @sebgrijalva ? Should I set this up?

**Comment by sebgrijalva** [comment]
I think it's a good idea, we might as well get used to it now, as the number of notebooks will keep growing.

**Comment by HGSilveri** [comment]
I know I said I'd do this, but actually it has to be done with the account that owns the repository, so I think it will be up to you, @lhenriet .

**Comment by lhenriet** [comment]
@HGSilveri you should be able to do it now.

**Comment by HGSilveri** [comment]
Ok, the app is installed on this repo. If you want to use it, go [here](https://app.reviewnb.com/), sign up and you should be able to select Pulser. It's not of much use right now, but once we have a PR with changes to notebooks, we should be able to try this out.

**Comment by sebgrijalva** [comment]
Thanks, this looks nice!

**Comment by HGSilveri** [comment]
Does it work for you, @sebgrijalva ?

**Comment by sebgrijalva** [comment]
Yes, I think so 

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/13460713/104922722-5ffab180-599b-11eb-8c84-b8e5e3369f61.png">

**Comment by HGSilveri** [comment]
Ok, great!
