### ISSUE TITLE
Cannot import Device or BaseDevice

### ISSUE THREAD

**Issue by Yoric** [pasqal-io/Pulser#699]
I'd like to write some code that takes as argument a device. Currently, both `Device` and `BaseDevice` are defined in `_device_datacls`, which marks them as private. Is there any better way to do this? If not, could either `Device` or `BaseDevice` be officially exported somewhere?

**Comment by HGSilveri** [comment]
`Device` and `VirtualDevice` are officially exported under `pulser.devices`, so you can import them from there. `BaseDevice` is an ABC and is purposefully not exported, as it is intended to be an internal class only. Why would you like to export it?

**Comment by Yoric** [comment]
Mmmh... Pyright informs me that:

```
"Device" is not exported from module "pulser.devices"
  Import from "pulser.devices._device_datacls" instead
```

**Comment by Yoric** [comment]
Apologies for the noise. It seems to be a Pyright error.
