### ISSUE TITLE
Upgrade to Qutip 5

### ISSUE THREAD

**Issue by HGSilveri** [pasqal-io/Pulser#730]
EDIT: On standby for eventual modification to the internals of `QutipEmulator` - for now, Qutip 5 is substantially worse than Qutip 4. 
The changes needed to go to Qutip 5 have been pushed to [this branch](https://github.com/pasqal-io/Pulser/tree/hs/qutip-5)

**Comment by HGSilveri** [comment]
I gave this a shot and the conclusions were underwhelming (to say the least):
- `Qobj` is not longer `ArrayLike`, so we have to explicitly call `full()` to use numpy ufuncs and sometimes go back to `Qobj`
- Some methods (eg `Qobj.extract_states()`, `Qobj.eliminate_states()`) were deleted without a substitute, so we have to implement them manually
- **Execution became dramatically slower**: On my laptop, `test_simulation.py` ran in 8.55s on `qutip==4.7.6`, now doesn't even complete in _10 minutes!_ (I gave up and interrupted it)

It's clear that Qutip 5 introduced changes that are incompatible with our current implementation in `pulser-simulation`. Until that changes, we should stick with Qutip 4.

**Comment by awennersteen** [comment]
Re: performance there appears to have been a few other reports of this that they were able to fix, but in some cases they're pretty low level

https://github.com/qutip/qutip/issues/2443
https://github.com/qutip/qutip/issues/2406

However, given #757 we might not be able to postpone this forever.

**Comment by HGSilveri** [comment]
Thanks for looking into this @awennersteen . So far, these changes have not been released yet so I can't tell whether they will help without getting into the weeds of installing qutip from source. As this is not urgent, I'll wait for the release before trying again.
