### ISSUE TITLE
How to get the parameters of the phase diagram?

### ISSUE THREAD

**Issue by ZongkaiLiu** [pasqal-io/Pulser#76]
Hello, this package is helpful in my research. I  really appreciate for your work. 
However, I am a little confused while reading the tutorial _Building 1D Rydberg Crystals.ipynb_. In the function `phase_diagram()` , the lobes of the phase diagram are draw by the `fill_between()` function. It seems that the parameters are already determined (`x = 2*(0.6+8*(y-1.2)**2)`). I do not know how to obtain these parameters.
I think it is better to get these parameters by using the eigensolver of Qutip or DMRG.

**Comment by sebgrijalva** [comment]
Hello, 
In the tutorial you mention there is a phase diagram of the different phases for detuning and Rabi frequency. but this is only an schematic picture, the parameters are indeed just filled parabolas. Obtaining precise phase transition points is a more delicate problem in which one investigates the closing of the energy gap or the scaling of the divergence of an order parameter (which as you said, could be done for example with a DMRG algorithm). We did not attempt to do this in the tutorial, but extracted these shapes from Fig. 2 of [this paper](https://arxiv.org/pdf/1707.04344.pdf).

Thank you for using Pulser and noticing that this was not explained. We will include this comment in the notebook.
