### ISSUE TITLE
Modify the `Channel.__repr__()` to use the one provided by dataclass

### ISSUE THREAD

**Issue by HGSilveri** [pasqal-io/Pulser#767]
Currently, we are manually defining `Channel.__repr__()` and are doing a poor job at keeping it up to date and showing all the relevant parameters.
I propose we instead rely on the default `repr` that's automatically generated in `dataclass`. 
If it makes sense to keep the current, "prettier" option, we can move it to `__str__()`

**Comment by RafaelMALima** [comment]
Mind if I do this?

**Comment by HGSilveri** [comment]
You're most welcome @RafaelMALima ! I'll assign it to you

**Comment by RafaelMALima** [comment]
Thats a dumb question, I just realised I had forgot to build the project before testing, haha. Everything seems to be working, I'll start drafting the PR.
