### ISSUE TITLE
Variable retarget time

### ISSUE THREAD

**Issue by HGSilveri** [pasqal-io/Pulser#78]
To more closely mimic the actual implementation, the retarget times should vary according to the last time a "target" command was added to a channel. The only criteria is that two "target" commands have to be spaced 220 ns. A retarget time is only added to enforce this rule. This will mean, in almost every case, that the target times will go down to 0.

It will have an effect on some tutorials, other than that it should be fine.

@sebgrijalva @lhenriet The only question is: do we want it in Pulser v0 or can we leave it for the next release?

**Comment by lhenriet** [comment]
I would be in favor of dealing with issues like that as soon as they appear.
