### ISSUE TITLE
Removing "rydberg_local2" from Chadoq2

### ISSUE THREAD

**Issue by HGSilveri** [pasqal-io/Pulser#81]
With the new mechanism for retargeting local channels, the "rydberg_local2" channel is no longer necessary for CZ gate implementations and I would guess it won't be added to Chadoq2, unless I'm missing something. As such, I was thinking I should remove it. Any objections @lhenriet @sebgrijalva ?

**Comment by sebgrijalva** [comment]
If it's not going to be added to Chadoq2, I'm inclined to have it removed.

**Comment by HGSilveri** [comment]
I'm not sure it won't, but that would be my guess. And anyway, if it ends up being added, it's always easy and non-conflicting to add it then.
